Update theme-indicator to filename lookup
Defra-Data-Science-Centre-of-Excellence/oiflib pull request #90
Opened 2021-04-13 09:26 UTC by EFT-Defra

Closes #88 by changing the theme-indicator to filename look up from the Goal-Target-Indicator naming convention to the Theme-Indicator-Chart naming convention.

I've also changed to using MappingProxyType from the standard library to create a read-only dictionary instead of using the third-party frozendict library.

2021-04-14 09:13 UTC, meganevparry reviewed
I'm a bit unsure of the three part code you have. Presume the first two numbers are theme and indicator. So 1-1 is Air Theme A Indicator 1. Is the third number the chart within an indicator where there are multiple? Is it OK that this dictionary always has a 1 for the third number? Presume where there are multiple charts within an indicator there could be multiple three part codes that apply. E.g. for B1, then water one could be 2-1-1 or 2-2-2. Not sure if that is an issue here or not... If this is fine, shall I continue to check if theme and indicator match and the third number is always one?

Also, the latest report does have a number scheme for charts. Charts in B1 are labelled B1a and B1b. Sometimes, just to be extract confusing, the label is something like C3ai, C3aii, C3bi, C3bii. I wonder if it would help to use the same naming convention for the code. It would be easier for a user cross referencing with the report, but imagine it wouldn't translate well for code. Maybe we will need another look-up table somewhere! The chart numbering is likely to change for each report though as indicators develop, so it couldn't be static.

2021-04-14 09:53 UTC, EFT-Defra commented
Hi @meganevparry,

Yes, this naming convention is a bit of a hack. The OpenSDG platform requires a three part numerical code to convert the input data and metadata into a website (the files literally have to be named indicator_#-#-#.csv), so the Theme-Indicator-Chart encoding used here is my work around. It does lead to a superfluous final -1 for indicators like A1 (1-1-1) that only have one chart but it does allow us to capture B1a (2-1-1) and B1b (2-1-2). I hadn't realised there were four part indicators and I'm not sure if OpenSDG can handle that or not...

However, the three part codes are only needed internally and we can use the encoding use in the report within the website itself for consistency. As you say, this will require another lookup!

See Defra-Data-Science-Centre-of-Excellence/OIF-Project-Management#117  and Defra-Data-Science-Centre-of-Excellence/OIF-Dashboard-Data#12 for how we got to where we are now...

2021-04-15 09:12 UTC, EFT-Defra commented on src/oiflib/_helper.py
>  )
This is the new look up

2021-04-15 09:13 UTC, EFT-Defra commented on src/oiflib/push.py
> +    return f"indicator_{tic_code}.csv"
This is the function that uses the lookup to set the CSV filename

2021-04-15 09:14 UTC, EFT-Defra commented on tests/test_push.py
>      assert returned == expected
This is the test that checks the function is doing what it should be.

2021-04-15 10:22 UTC, EFT-Defra commented
Some questions about the report codes:
- C3ai and C3aii aren't different visualisations of the same data, why aren't they C3a and C3b?
- C4 includes four different maps, currently they will be embedded as a single image but shouldn't they be separate visualisations in the future (i.e. C4a, C4b, C4c, and C4d)
- C7a and C7b both contain two maps, why aren't they labelled individually?
- D4 contains 5 different visualisation, why aren't they labelled individually?
- D7i and D7ii are missing their third part, for consistency, shouldn't they be labelled D7ai and D7aii?

2021-04-15 13:59 UTC, meganevparry commented on src/oiflib/_helper.py
> +        "C2ai": "3-2-1-a",
Labelled C2i and C2ii in the report (as only one component so no b). The coding looks correct, as you would still want to see these charts side by side ideally. Can see how adding the a makes it more logical for matching the 4 part code. We just need to make sure users type in the right original chart no and don't just copy from the report. Or we could change to C2i here or add an a in the report so they match.

2021-04-15 14:37 UTC, meganevparry commented on src/oiflib/_helper.py
> +        "C3ai": "3-3-1-a",
C3 is a bit of a weird one, not really consistent with our approach to naming. C3ai and ii are not actually based around the same data, but are both about seals. C3b is about marine birds. You could argue we should have labelled it differently in the report, but C3ai and ii are related so hard to think of an alternative. Perhaps they should be C3a, b and c. However, think it would still be fine to have the seal charts as 2 tabs on the same page and speak about all the seals together so could keep it like this to match the report. Jasmine and Simon may have a view.

2021-04-15 14:39 UTC, meganevparry requested changes
This looks good. I've just suggested one change for C2, and flagged something we might want to raise with Jasmine and Simon.

2021-04-16 09:03 UTC, EFT-Defra commented on src/oiflib/_helper.py
>  )
Alphanumeric Theme-Indicator to numeric Theme-Indicator-1 mappings

2021-04-16 09:46 UTC, meganevparry approved these changes

2021-04-16 09:47 UTC, merged